# Generated by Django 5.2.5 on 2025-09-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganado',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='comprador_telefono',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='fecha_fallecimiento',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='razon_fallecimiento',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='razon_venta',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='valor_venta',
        ),
    ]
