# Generated by Django 5.2.5 on 2025-10-03 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="fecha_produccion",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="fecha_venta",
        ),
        migrations.AddField(
            model_name="ventaproducto",
            name="fecha_venta",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="ganado",
            name="descripcion_peñe",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Descripción de la Preñez",
            ),
        ),
        migrations.AlterField(
            model_name="ganado",
            name="fecha_peñe",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Preñez"
            ),
        ),
        migrations.AlterField(
            model_name="ganado",
            name="peñe",
            field=models.CharField(
                choices=[
                    ("NATURAL", "Natural"),
                    ("INSEMINACION", "Inseminación"),
                    ("NO_APLICA", "No Aplica"),
                ],
                default="NO_APLICA",
                max_length=15,
                verbose_name="Tipo de Preñez",
            ),
        ),
        migrations.CreateModel(
            name="FechaProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fechas_produccion",
                        to="inventario.producto",
                    ),
                ),
            ],
        ),
    ]
