# Generated by Django 5.2.5 on 2025-10-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_remove_producto_fecha_produccion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventaproducto",
            name="valor_compra",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
