# Generated by Django 5.2.5 on 2025-09-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0001_initial'),
        ('inventario', '0002_ubicacion_movimientoinventario_producto_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej: Diesel, Gasolina', max_length=50)),
                ('cantidad_galones', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ControlPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo', models.CharField(help_text='Ej: Herbicida, Insecticida', max_length=50)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(help_text='Ej: Tractor, Guadaña', max_length=100)),
                ('descripcion_tarea', models.TextField()),
                ('fecha_programada', models.DateField()),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(help_text='Unidades, ml, etc.')),
                ('fecha_caducidad', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Potrero La Loma', max_length=100)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.categoria'),
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Heno, Silo de maíz, Sal mineral', max_length=100)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Arete N° 123', max_length=50, unique=True)),
                ('raza', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('potrero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.potrero')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
