# Generated by Django 5.2.5 on 2025-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_ventaproducto_valor_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventaproducto",
            name="cantidad_vendida",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ventaproducto",
            name="fecha_produccion_venta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ventaproducto",
            name="precio_unitario_venta",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
