# Generated by Django 5.2.5 on 2025-10-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_ventaproducto_cantidad_vendida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dotacion",
            name="camisa_franela",
            field=models.BooleanField(default=False, verbose_name="Camisa/franela"),
        ),
        migrations.AlterField(
            model_name="dotacion",
            name="zapato",
            field=models.BooleanField(default=False, verbose_name="Zapatos/botas"),
        ),
    ]
