# Generated by Django 5.2.5 on 2025-09-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_alimento_imagen_combustible_imagen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="alimentos/"),
        ),
        migrations.AlterField(
            model_name="combustible",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="combustible/"),
        ),
        migrations.AlterField(
            model_name="controlplaga",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="control_plagas/"),
        ),
        migrations.AlterField(
            model_name="ganado",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="ganado/"),
        ),
        migrations.AlterField(
            model_name="mantenimiento",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="mantenimiento/"),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="medicamentos/"),
        ),
        migrations.AlterField(
            model_name="potrero",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="potreros/"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
