# Generated by Django 5.2.5 on 2025-10-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_alter_dotacion_camisa_franela_alter_dotacion_zapato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicamento",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
