# Generated by Django 5.2.5 on 2025-09-16 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_alimento_imagen_alter_combustible_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='alimentos'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='combustibles'),
        ),
        migrations.AlterField(
            model_name='controlplaga',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='control_plagas'),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ganados'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mantenimientos'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='medicamentos'),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='potreros'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='productos'),
        ),
    ]
