# Generated by Django 5.2.5 on 2025-09-18 09:35

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_alimento_imagen_alter_combustible_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='cantidad_kg',
        ),
        migrations.AddField(
            model_name='alimento',
            name='cantidad_kg_ingresada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad (Kg)'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='cantidad_kg_usada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='alimento',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alimento',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
