# Generated by Django 5.2.5 on 2025-09-18 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_alimento_cantidad_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combustible',
            name='cantidad_galones',
        ),
        migrations.AddField(
            model_name='combustible',
            name='cantidad_galones_ingresada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Galones ingresados'),
        ),
        migrations.AddField(
            model_name='combustible',
            name='cantidad_galones_usados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
