# Generated by Django 5.2.5 on 2025-09-18 09:58

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0003_etiqueta_parent_proveedor_telefono_ubicacion_imagen_and_more'),
        ('inventario', '0010_remove_combustible_cantidad_galones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlplaga',
            name='cantidad_litros',
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='cantidad_ingresada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='cantidad_usada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion'),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='unidad_medida',
            field=models.CharField(choices=[('L', 'Litros (L)'), ('ml', 'Mililitros (ml)'), ('Kg', 'Kilogramos (Kg)'), ('g', 'Gramos (g)')], default='L', max_length=2),
        ),
    ]
