# Generated by Django 5.2.5 on 2025-09-18 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_controlplaga_cantidad_litros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganado',
            name='estado',
            field=models.CharField(choices=[('VIVO', 'Vivo'), ('FALLECIDO', 'Fallecido'), ('VENDIDO', 'Vendido')], default='VIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='ganado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ganado',
            name='genero',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='ganado',
            name='nombre_vacuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ganado',
            name='parto',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('INSEMINACION', 'Inseminación'), ('ARTIFICIAL', 'Artificial'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=15),
        ),
        migrations.AddField(
            model_name='ganado',
            name='proxima_vacunacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ganado',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='raza',
            field=models.CharField(choices=[('VACA', 'Vaca'), ('TORO', 'Toro'), ('CABALLO', 'Caballo'), ('YEGUA', 'Yegua'), ('PERRO', 'Perro'), ('GATO', 'Gato'), ('GALLINA', 'Gallina'), ('GALLO', 'Gallo'), ('PATO', 'Pato')], default='VACA', max_length=10),
        ),
    ]
