# Generated by Django 5.2.5 on 2025-09-18 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_ganado_estado_ganado_fecha_ingreso_ganado_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_programada',
            new_name='fecha_proximo_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion_tarea',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
