# Generated by Django 5.2.5 on 2025-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_rename_fecha_programada_mantenimiento_fecha_proximo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='tamano',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], default='M', max_length=1),
        ),
    ]
