# Generated by Django 5.2.5 on 2025-09-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0005_proveedor_correo_electronico_proveedor_imagen_and_more'),
        ('inventario', '0014_potrero_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('U', 'Unidades'), ('Kg', 'Kilogramos (Kg)'), ('g', 'Gramos (g)'), ('L', 'Litros (L)'), ('ml', 'Mililitros (ml)')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
