# Generated by Django 5.2.5 on 2025-09-18 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0005_proveedor_correo_electronico_proveedor_imagen_and_more'),
        ('inventario', '0015_alimento_proveedor_controlplaga_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='fecha_caducidad',
            new_name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='alimento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='combustible',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por galón'),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.categoria'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='unidad_medida',
            field=models.CharField(choices=[('U', 'Unidad'), ('Kg', 'Kilogramos (Kg)'), ('g', 'Gramos (g)'), ('L', 'Litros (L)'), ('ml', 'Mililitros (ml)')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='lote',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
