# Generated by Django 5.2.5 on 2025-09-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_rename_fecha_caducidad_medicamento_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='lote',
        ),
    ]
