# Generated by Django 5.2.5 on 2025-09-19 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_remove_medicamento_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='cantidad',
            new_name='cantidad_ingresada',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='cantidad_usada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_produccion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='tamano',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], default='M', max_length=1, verbose_name='Tamaño'),
        ),
    ]
