# Generated by Django 5.2.5 on 2025-09-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0005_proveedor_correo_electronico_proveedor_imagen_and_more'),
        ('inventario', '0018_rename_cantidad_medicamento_cantidad_ingresada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.categoria'),
        ),
    ]
