# Generated by Django 5.2.5 on 2025-09-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0005_proveedor_correo_electronico_proveedor_imagen_and_more'),
        ('inventario', '0019_alimento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='caracteristicas.etiqueta'),
        ),
    ]
