# Generated by Django 5.2.6 on 2025-09-21 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_alimento_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=150)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('numero', models.CharField(help_text='Teléfono de contacto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('numero', models.CharField(help_text='Teléfono de contacto', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='lugar_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='inventario.lugarmantenimiento'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_realizado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('metodo_pago', models.CharField(help_text='Ej: Efectivo, Transferencia', max_length=50)),
                ('forma_pago', models.CharField(choices=[('M', 'Mensual'), ('Q', 'Quincenal'), ('S', 'Semanal')], default='M', max_length=1)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Dotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camisa_franela', models.BooleanField(default=False)),
                ('pantalon', models.BooleanField(default=False)),
                ('zapato', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotaciones', to='inventario.trabajador')),
            ],
        ),
    ]
