# Generated by Django 5.2.5 on 2025-09-22 23:25

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0005_proveedor_correo_electronico_proveedor_imagen_and_more'),
        ('inventario', '0021_lugarmantenimiento_trabajador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dotacion',
            options={'verbose_name': 'Dotación', 'verbose_name_plural': 'Dotaciones'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='controlplaga',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='nombre_vacuna',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='parto',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='potrero',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='proxima_vacunacion',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='vacunado',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='lugar_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='alimento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='combustible',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='combustible',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='combustible',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion'),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='dotacion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ganado',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ganado',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso (Kg)'),
        ),
        migrations.AddField(
            model_name='ganado',
            name='proxima_vacunacion_1',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Vacunación 1 (Vacuna y Fecha)'),
        ),
        migrations.AddField(
            model_name='ganado',
            name='proxima_vacunacion_2',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Vacunación 2 (Vacuna y Fecha)'),
        ),
        migrations.AddField(
            model_name='ganado',
            name='proxima_vacunacion_3',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Vacunación 3 (Vacuna y Fecha)'),
        ),
        migrations.AddField(
            model_name='lugarmantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='lugarmantenimiento',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='lugarmantenimiento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='lugares_mantenimiento',
            field=models.ManyToManyField(blank=True, to='inventario.lugarmantenimiento'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='pago',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='potrero',
            name='cambio_con_potrero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambia_con', to='inventario.potrero', verbose_name='Cambiar con potrero'),
        ),
        migrations.AddField(
            model_name='potrero',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='potrero',
            name='empastado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='potrero',
            name='fecha_cambio_potrero',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cambio'),
        ),
        migrations.AddField(
            model_name='potrero',
            name='fumigado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='potrero',
            name='proximo_empastado',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Empastado'),
        ),
        migrations.AddField(
            model_name='potrero',
            name='proximo_fumigado',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Fumigado'),
        ),
        migrations.AddField(
            model_name='potrero',
            name='proximo_rozado',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Rozado'),
        ),
        migrations.AddField(
            model_name='potrero',
            name='rozado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='compradores',
            field=models.JSONField(blank=True, default=list, help_text="Añadir compradores en formato JSON. Ej: [{'nombre': 'Juan', 'telefono': '321...', 'valor': 50000}]"),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por Unidad/Kg/L'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='raza',
            field=models.CharField(blank=True, max_length=100, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('U', 'Unidades'), ('Kg', 'Kilogramos (Kg)'), ('L', 'Litros (L)')], default='U', max_length=2),
        ),
        migrations.AddField(
            model_name='ganado',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.animal', verbose_name='Animal'),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos (g)'), ('ml', 'Mililitros (ml)'), ('Kg', 'Kilogramos (Kg)'), ('L', 'Litros (L)')], default='ml', max_length=2)),
                ('dosis_crecimiento', models.CharField(blank=True, max_length=100, verbose_name='Dosis por Crecimiento')),
                ('dosis_edad', models.CharField(blank=True, max_length=100, verbose_name='Dosis por Edad')),
                ('dosis_peso', models.CharField(blank=True, max_length=100, verbose_name='Dosis por Peso')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=1000)),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.etiqueta')),
                ('proveedores', models.ManyToManyField(blank=True, to='caracteristicas.proveedor')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='ganado',
            name='vacunas',
            field=models.ManyToManyField(blank=True, to='inventario.vacuna'),
        ),
    ]
