# Generated by Django 5.2.5 on 2025-09-22 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0005_proveedor_correo_electronico_proveedor_imagen_and_more'),
        ('inventario', '0022_animal_alter_dotacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganado',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='vacunas',
        ),
        migrations.AlterModelOptions(
            name='dotacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={},
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='controlplaga',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='controlplaga',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='dotacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='proxima_vacunacion_1',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='proxima_vacunacion_2',
        ),
        migrations.RemoveField(
            model_name='ganado',
            name='proxima_vacunacion_3',
        ),
        migrations.RemoveField(
            model_name='lugarmantenimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='lugarmantenimiento',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='lugarmantenimiento',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='lugares_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='cambio_con_potrero',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='empastado',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='fecha_cambio_potrero',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='fumigado',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='proximo_empastado',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='proximo_fumigado',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='proximo_rozado',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='rozado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='compradores',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_unidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='alimento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='controlplaga',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.proveedor'),
        ),
        migrations.AddField(
            model_name='ganado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ganado',
            name='nombre_vacuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ganado',
            name='parto',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('INSEMINACION', 'Inseminación'), ('ARTIFICIAL', 'Artificial'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=15),
        ),
        migrations.AddField(
            model_name='ganado',
            name='potrero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.potrero'),
        ),
        migrations.AddField(
            model_name='ganado',
            name='proxima_vacunacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ganado',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='lugar_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='inventario.lugarmantenimiento'),
        ),
        migrations.AddField(
            model_name='potrero',
            name='tamano',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], default='M', max_length=1, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.proveedor'),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='raza',
            field=models.CharField(choices=[('VACA', 'Vaca'), ('TORO', 'Toro'), ('CABALLO', 'Caballo'), ('YEGUA', 'Yegua'), ('PERRO', 'Perro'), ('GATO', 'Gato'), ('GALLINA', 'Gallina'), ('GALLO', 'Gallo'), ('PATO', 'Pato')], default='VACA', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('U', 'Unidades'), ('Kg', 'Kilogramos (Kg)'), ('g', 'Gramos (g)'), ('L', 'Litros (L)'), ('ml', 'Mililitros (ml)')], default='U', max_length=2),
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
    ]
