# Generated by Django 5.2.5 on 2025-09-23 00:00

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "caracteristicas",
            "0005_proveedor_correo_electronico_proveedor_imagen_and_more",
        ),
        ("inventario", "0023_remove_ganado_animal_remove_vacuna_etiqueta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Animal",
                "verbose_name_plural": "Tipos de Animales",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Comprador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Comprador",
                "verbose_name_plural": "Compradores",
            },
        ),
        migrations.AlterModelOptions(
            name="dotacion",
            options={"verbose_name": "Dotación", "verbose_name_plural": "Dotaciones"},
        ),
        migrations.AlterModelOptions(
            name="trabajador",
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
        migrations.RemoveField(
            model_name="alimento",
            name="proveedor",
        ),
        migrations.RemoveField(
            model_name="controlplaga",
            name="proveedor",
        ),
        migrations.RemoveField(
            model_name="ganado",
            name="fecha_ingreso",
        ),
        migrations.RemoveField(
            model_name="ganado",
            name="nombre_vacuna",
        ),
        migrations.RemoveField(
            model_name="ganado",
            name="potrero",
        ),
        migrations.RemoveField(
            model_name="ganado",
            name="proxima_vacunacion",
        ),
        migrations.RemoveField(
            model_name="ganado",
            name="vacunado",
        ),
        migrations.RemoveField(
            model_name="mantenimiento",
            name="lugar_mantenimiento",
        ),
        migrations.RemoveField(
            model_name="potrero",
            name="tamano",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="proveedor",
        ),
        migrations.AddField(
            model_name="alimento",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción del alimento.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alimento",
            name="proveedores",
            field=models.ManyToManyField(
                blank=True, related_name="alimentos", to="caracteristicas.proveedor"
            ),
        ),
        migrations.AddField(
            model_name="combustible",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Notas sobre el combustible.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="combustible",
            name="proveedores",
            field=models.ManyToManyField(
                blank=True, related_name="combustibles", to="caracteristicas.proveedor"
            ),
        ),
        migrations.AddField(
            model_name="combustible",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="controlplaga",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción del producto de control de plagas.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="controlplaga",
            name="proveedores",
            field=models.ManyToManyField(
                blank=True,
                related_name="controles_plaga",
                to="caracteristicas.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="ganado",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Notas o descripción del animal.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ganado",
            name="peso_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Peso (Kg)",
            ),
        ),
        migrations.AddField(
            model_name="lugarmantenimiento",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción del lugar de mantenimiento.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lugarmantenimiento",
            name="proveedores",
            field=models.ManyToManyField(
                blank=True,
                related_name="lugares_mantenimiento",
                to="caracteristicas.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="lugarmantenimiento",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción detallada del mantenimiento realizado o por realizar.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="lugares_mantenimiento",
            field=models.ManyToManyField(
                blank=True,
                related_name="mantenimientos",
                to="inventario.lugarmantenimiento",
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción y notas sobre el medicamento.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="proveedores",
            field=models.ManyToManyField(
                blank=True, related_name="medicamentos", to="caracteristicas.proveedor"
            ),
        ),
        migrations.AddField(
            model_name="potrero",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción y estado del potrero.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="potrero",
            name="empastado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="potrero",
            name="fecha_intercambio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="potrero",
            name="fecha_proxima_fumigacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="potrero",
            name="fecha_proximo_empaste",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="potrero",
            name="fecha_proximo_rozado",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="potrero",
            name="fumigado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="potrero",
            name="intercambio_con_potrero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intercambios_programados",
                to="inventario.potrero",
            ),
        ),
        migrations.AddField(
            model_name="potrero",
            name="rozado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción detallada del producto.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ganado",
            name="raza",
            field=models.CharField(
                blank=True,
                help_text="Ej: Holstein, Angus",
                max_length=100,
                verbose_name="Raza",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.CharField(
                choices=[
                    ("U", "Unidades"),
                    ("Kg", "Kilogramos (Kg)"),
                    ("L", "Litros (L)"),
                ],
                default="U",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="ganado",
            name="animal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.animal",
                verbose_name="Tipo de Animal",
            ),
        ),
        migrations.CreateModel(
            name="Vacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("disponible", models.BooleanField(default=True)),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[
                            ("g", "Gramos (g)"),
                            ("ml", "Mililitros (ml)"),
                            ("Kg", "Kilogramos (Kg)"),
                            ("L", "Litros (L)"),
                            ("U", "Unidad"),
                        ],
                        default="U",
                        max_length=2,
                    ),
                ),
                (
                    "dosis_crecimiento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dosis por Crecimiento"
                    ),
                ),
                (
                    "dosis_edad",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dosis por Edad"
                    ),
                ),
                (
                    "dosis_peso",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dosis por Peso"
                    ),
                ),
                ("fecha_compra", models.DateField(default=django.utils.timezone.now)),
                ("fecha_vencimiento", models.DateField()),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la vacuna.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "imagen",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "etiqueta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="caracteristicas.etiqueta",
                    ),
                ),
                (
                    "proveedores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vacunas",
                        to="caracteristicas.proveedor",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="caracteristicas.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacuna",
                "verbose_name_plural": "Vacunas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RegistroVacunacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_aplicacion",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("fecha_proxima_dosis", models.DateField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "ganado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacunaciones",
                        to="inventario.ganado",
                    ),
                ),
                (
                    "vacuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="inventario.vacuna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Vacunación",
                "verbose_name_plural": "Registros de Vacunación",
                "ordering": ["-fecha_aplicacion"],
            },
        ),
        migrations.CreateModel(
            name="VentaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.comprador",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta de Producto",
                "verbose_name_plural": "Ventas de Productos",
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="compradores",
            field=models.ManyToManyField(
                blank=True,
                related_name="productos_comprados",
                through="inventario.VentaProducto",
                to="inventario.comprador",
            ),
        ),
    ]