# Generated by Django 5.2.5 on 2025-09-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "caracteristicas",
            "0005_proveedor_correo_electronico_proveedor_imagen_and_more",
        ),
        ("inventario", "0024_animal_comprador_alter_dotacion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacuna",
            name="etiqueta",
        ),
        migrations.AddField(
            model_name="vacuna",
            name="etiquetas",
            field=models.ManyToManyField(blank=True, to="caracteristicas.etiqueta"),
        ),
    ]
