# Generated by Django 5.2.5 on 2025-09-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "caracteristicas",
            "0005_proveedor_correo_electronico_proveedor_imagen_and_more",
        ),
        ("inventario", "0025_change_vacuna_etiqueta_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alimento",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="combustible",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="controlplaga",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="lugarmantenimiento",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="medicamento",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="vacuna",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="alimento",
            name="ubicaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="alimentos_ubicados",
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="combustible",
            name="ubicaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="combustibles_ubicados",
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="controlplaga",
            name="ubicaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="controles_plaga_ubicados",
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="lugarmantenimiento",
            name="ubicaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="lugares_mantenimiento_ubicados",
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="ubicaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="medicamentos_ubicados",
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="ubicaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="productos_ubicados",
                to="caracteristicas.ubicacion",
            ),
        ),
        migrations.AddField(
            model_name="vacuna",
            name="ubicaciones",
            field=models.ManyToManyField(
                blank=True,
                related_name="vacunas_ubicadas",
                to="caracteristicas.ubicacion",
            ),
        ),
    ]
