# Generated by Django 5.2.5 on 2025-09-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_remove_alimento_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('APARTADO', 'Apartado'), ('VENDIDO', 'Vendido')], default='DISPONIBLE', max_length=10),
        ),
    ]
