# Generated by Django 5.2.5 on 2025-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='valor_abono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
