# Generated by Django 5.2.5 on 2025-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_ventaproducto_valor_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
