# Generated by Django 5.2.5 on 2025-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_vacuna_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganado',
            name='parto',
        ),
        migrations.AddField(
            model_name='ganado',
            name='pene',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('INSEMINACION', 'Inseminación'), ('ARTIFICIAL', 'Artificial'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=15),
        ),
    ]
