# Generated by Django 5.2.5 on 2025-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0030_remove_ganado_parto_ganado_pene"),
    ]

    operations = [
        migrations.AddField(
            model_name="ganado",
            name="estado_salud",
            field=models.CharField(
                choices=[
                    ("ENFERMA", "Enferma"),
                    ("TRATAMIENTO", "En Tratamiento"),
                    ("RECUPERANDOSE", "Recuperándose"),
                    ("CURADA", "Curada"),
                    ("NO_TIENE_NADA", "No tiene nada"),
                ],
                default="NO_TIENE_NADA",
                max_length=20,
            ),
        ),
    ]
