# Generated by Django 5.2.5 on 2025-09-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_remove_ganado_parto_ganado_comprador_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ganado',
        #     name='parto',
        # ),
    ]
