# Generated by Django 5.2.5 on 2025-09-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_remove_ganado_parto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganado',
            name='comprador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comprador'),
        ),
    ]
