# Generated by Django 5.2.5 on 2025-09-25 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0031_ganado_estado_salud"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_aplicacion",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "ganado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicamentos_aplicados",
                        to="inventario.ganado",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_aplicacion",
                        to="inventario.medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Medicamento",
                "verbose_name_plural": "Registros de Medicamentos",
                "ordering": ["-fecha_aplicacion"],
            },
        ),
    ]
