# Generated by Django 5.2.5 on 2025-09-18 00:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0002_etiqueta_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_etiquetas', to='caracteristicas.etiqueta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del proveedor', max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='link',
            field=models.URLField(blank=True, help_text='Enlace a la ubicación en un mapa'),
        ),
    ]
