# Generated by Django 5.2.5 on 2025-09-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0003_etiqueta_parent_proveedor_telefono_ubicacion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
