# Generated by Django 5.2.5 on 2025-09-18 19:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0004_ubicacion_barrio_ubicacion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_local',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del lugar/local'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caracteristicas.ubicacion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del proveedor'),
        ),
    ]
